name: Release

on: 
  push:
    paths-ignore:
    - 'archive/**'
    - '**/README.md'
    - '**/LICENSE'
    - '**/.gitignore'

jobs:
  build-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout DxWiFi Repository
        uses: actions/checkout@v2
        with: 
          submodules: recursive
      
      - name: Get Dependencies
        run: sudo apt update && sudo apt install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf qemu-user-static debootstrap -y

      - name: Build cross-compilation toolchain
        run: |
          sudo qemu-debootstrap --arch armhf buster /mnt/data/armhf http://deb.debian.org/debian/
          sudo chroot /mnt/data/armhf /bin/bash -c "apt-get install libpcap-dev"
          sudo chroot /mnt/data/armhf /bin/bash -c "apt-get install libgpiod-dev"

      - name: Configure CMake
        working-directory: tx-rx
        shell: bash
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DPLATFORM=armhf -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        working-directory: tx-rx
        shell: bash
        run: cmake --build build --parallel 6
